### ISSUE TITLE
Switch rule gen_minimap_input to use conda environment instead of a container

### ISSUE THREAD

**Issue by leoisl** [iqbal-lab-org/pling#49]
See https://github.com/iqbal-lab-org/pling/blob/7dbd4877183fc07e133f4d2ea0ffcfa1dd237d7c/pling/anno_snakemake/Snakefile#L77-L78

I switched to container because I was having issues installing `bakta` through `conda`, but I should have dug deeper and kept the `conda` env. Note that we also need to change the `gen_minimap_input.py` script to have a CLI and be callable from `shell`. Doing this will remove having `singularity` as a dependency, which is worth it

**Comment by babayagaofficial** [comment]
Fixed in v1.0.3
