### ISSUE TITLE
Pling ran successfully, but html files are empty

### ISSUE THREAD

**Issue by ayoraind** [iqbal-lab-org/pling#66]
Dear Pling developers,

Thanks for taking the time to develop this incredible tool. I installed and ran Pling successfully today. All expected output files as per https://github.com/iqbal-lab-org/pling/tree/main?tab=readme-ov-file#description-and-output were present. However, on checking the html files generated within the containment/containment_communities/visualisations/ directory, I could not see any visible plasmid networks. Is there a mistake from my end?
Unfortunately, Github does not allow me to upload any of the html files for your perusal.

![image](https://github.com/iqbal-lab-org/pling/assets/43066737/1a544bd1-5adf-43ae-956f-23befba0ff10)

**Comment by babayagaofficial** [comment]
Hi, did you change the directory structure in any way? For the htmls to work, the directory structure for the folder which contains `graphs` (folder with html files), `libs` and `index.html` needs to remain the same -- the htmls are encoded to use files from `libs`.
If you didn't, can you send me some screenshots of what you see when you open the html?

**Comment by ayoraind** [comment]
@babayagaofficial, thank you for your response. Ah! yes, I changed the directory structure. I assumed that the html files within the ´graphs´ folder could be copied (from the cloud server to a local PC) independently of the ´libs´ folder. On copying the whole `communities` folder which hosts the ´graph´ and the ´lib´ folder, I was able to visualize the networks. You can close the issue. Thanks.
