### ISSUE TITLE
Preinstalled Container options to run pling (docker,singularity)

### ISSUE THREAD

**Issue by replikation** [iqbal-lab-org/pling#68]
Dear dev,

Looking at all the dependencies of pling, is there a single container available (e.g., docker or singularity) containing all the preinstalled dependencies and envs that pling needs (so i can start the container and run pling inside)? Otherwise, it looks hacky to install with the various Python versions in a stable and reproducible manner, especially for workflows or routine applications. 

Best, and thank you.

**Comment by iqbal-lab** [comment]
Hi there
1. Apologies you’ve had problems,  @babayagaofficial has  been working to eliminate the barriers to a simple bioconda installation (bioconda would also automatically generate containers). So this is not just "on the roadmap ", but in progress.
2. @babayagaofficial is on vacation for 10 days, but will get back to you soon after that

All the best
Zam

**Comment by replikation** [comment]
Thanks for the reply. A single bioconda install recipe would be great.
