### ISSUE TITLE
Unknown error - aborted execution - no log info 

### ISSUE THREAD

**Issue by javiefernandez** [iqbal-lab-org/pling#75]
Hi there!! 
I have been running pling last week without any problem (after a few simple formatting issues) with a collection of around 450 elements.
Now I changed to a bigger collection and it is crashing. Unfortunately I can't figure out what the issue is. 
For this running I have not changed any parameter (just tried with 2 different batch sizes). 
Here you find the snakemake log.

[Sun Sep 15 20:39:00 2024]
Finished job 118.
25 of 1004 steps (2%) done
[Sun Sep 15 20:40:02 2024]
Finished job 112.
26 of 1004 steps (3%) done
[Sun Sep 15 20:41:01 2024]
Finished job 449.
27 of 1004 steps (3%) done
[Sun Sep 15 20:41:16 2024]
Finished job 2.
28 of 1004 steps (3%) done
[Sun Sep 15 20:41:17 2024]
Finished job 448.
29 of 1004 steps (3%) done
[Sun Sep 15 20:41:33 2024]
Finished job 840.
30 of 1004 steps (3%) done
[Sun Sep 15 20:42:24 2024]
Finished job 58.
31 of 1004 steps (3%) done
Shutting down, this might take some time.
Exiting because a job execution failed. **Look above for error message (ABOVE THERE IS NOTHING VALUABLE TO INVESTIGATE FURTHER)**
Complete log: .snakemake/log/...

Am I missing something? Any advice where to look for more details about the error?
Thanks a lot for this amazing tool!
Best regards,
Javier

**Comment by iqbal-lab** [comment]
Hi there - apologies, the reply will be slightly delayed, as Daria is on vacation until Wednesday. Couple of questions 
1. would it be permissible to share the data so she could try to reproduce it?
2. you get the same error irrespective of batch size then (when you tried two)?
3. Any chance there are duplicated plasmid ids or anything funny like that? (anyway should not crash, just guessing)

**Comment by javiefernandez** [comment]
Hi! thanks for the prompt answer!
I just figured out the problem and was on my end, some fasta files had more than one element inside (downloaded from plsdb). Users just keep that in mind!
Though still not finished is running smoothly so I guess we can close (or delete?) this issue.
Thanks again for this amazing tool and @babayagaofficial enjoy your vacations!
